### PR TITLE
Add an option to update comments

### LINKED ISSUE #11: Update the last comment instead of adding a new one
Can we get an option to update the last comment instead of creating a new one every time?

Very similar to the approach on https://github.com/EnricoMi/publish-unit-test-result-action where we can set the `comment_mode` to either `update last` or `create new`.

### PR DESCRIPTION
**Pull request by Chris-V**
Adds an option to update the first comment posted by the action instead of posting a new one every time. The option is disabled by default to avoid breaking changes and requires a non-empty title.

Fixes #11

### CODE REVIEW

**Comment by YashNagayach95** [comment]
When we are planning to merge this?

**Comment by sammcj** [comment]
Really keen to see this merged in if possible @Madrapps !

**Comment by thsaravana** [comment]
Need something to check this out. If everything is good, will merge it this weekend :)

**Comment by YashNagayach95** [comment]
> Need something to check this out. If everything is good, will merge it this weekend :)

Waiting from long time now 👍🏿

**Comment by sammcj** [comment]
Thanks for merging mate

**Comment by thsaravana** [comment]
Please try using `uses: madrapps/jacoco-report@main` for now and report if you find any errors. I have a couple more issues to fix and post that will release the `v1.3` tag.
Thanks @Chris-V for this feature improvement. Great work!

**Comment by tuomoa** [comment]
@thsaravana Is there going to be a release soon? I would prefer using released version instead of just main / random commit from main.

**Comment by YashNagayach95** [comment]
Waiting for v1.3

**Pull request merged**
